-- MySQL Script generated by MySQL Workbench
-- 05/19/15 10:31:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecotron
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecotron` ;

-- -----------------------------------------------------
-- Schema ecotron
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecotron` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ecotron` ;

-- -----------------------------------------------------
-- Table `ecotron`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Type` (
  `idType` INT NOT NULL,
  `nomType` VARCHAR(45) NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Lieux_Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Lieux_Archive` (
  `idLieux_Archive` INT NOT NULL,
  `plateforme` VARCHAR(45) NULL,
  `batiment` VARCHAR(45) NULL,
  `salle` VARCHAR(45) NULL,
  `paclard` INT NULL,
  `colonne` INT NULL,
  PRIMARY KEY (`idLieux_Archive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Fournisseur` (
  `idFournisseur` INT NOT NULL,
  `nomFournisseur` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idFournisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `nomUtilisateur` VARCHAR(45) NULL,
  `prenomUtilisateur` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `identifiantUtilisateur` VARCHAR(45) NULL,
  `mdpUtilisateur` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Planning_Occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Planning_Occupation` (
  `idPlanning_Occupation` INT NOT NULL,
  `dateDebut` DATETIME NULL,
  `dateFin` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPlanning_Occupation`, `idUtilisateur`),
  INDEX `fk_Planning_Occupation_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Panne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Panne` (
  `idPanne` INT NOT NULL,
  `nomPanne` VARCHAR(45) NULL,
  `datePanne` DATETIME NULL,
  `finPanne` DATETIME NULL,
  `description` VARCHAR(200) NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPanne`, `idUtilisateur`),
  INDEX `fk_Panne_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Categorie` (
  `idCategorie` INT NOT NULL,
  `nomCategorie` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement` (
  `idEquipement` INT NOT NULL,
  `etiquette` INT NULL,
  `nomEquiment` VARCHAR(45) NULL,
  `idType` INT NOT NULL,
  `idLieux_Archive` INT NOT NULL,
  `idFournisseur` INT NOT NULL,
  `idPlanning_Occupation` INT NOT NULL,
  `idPanne` INT NOT NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idType`, `idLieux_Archive`, `idFournisseur`, `idPlanning_Occupation`, `idPanne`, `idCategorie`),
  INDEX `fk_Equipement_Type_idx` (`idType` ASC),
  INDEX `fk_Equipement_Lieux_Archive1_idx` (`idLieux_Archive` ASC),
  INDEX `fk_Equipement_Fournisseur1_idx` (`idFournisseur` ASC),
  INDEX `fk_Equipement_Planning_Occupation1_idx` (`idPlanning_Occupation` ASC),
  INDEX `fk_Equipement_Panne1_idx` (`idPanne` ASC),
  INDEX `fk_Equipement_Categorie1_idx` (`idCategorie` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Document` (
  `idDocument` INT NOT NULL,
  `document` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement_has_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement_has_Document` (
  `idEquipement` INT NOT NULL,
  `idDocument` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idDocument`),
  INDEX `fk_Equipement_has_Document_Document1_idx` (`idDocument` ASC),
  INDEX `fk_Equipement_has_Document_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Entretient` (
  `idEntretient` INT NOT NULL,
  `dateEntretient` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idEntretient`, `idUtilisateur`),
  INDEX `fk_Entretient_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement_has_Entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement_has_Entretient` (
  `idEquipement` INT NOT NULL,
  `idEntretient` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idEntretient`),
  INDEX `fk_Equipement_has_Entretient_Entretient1_idx` (`idEntretient` ASC),
  INDEX `fk_Equipement_has_Entretient_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Liaison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Liaison` (
  `idLiaison` INT NOT NULL,
  `idEquipement1` INT NOT NULL,
  `idEquipement2` INT NOT NULL,
  PRIMARY KEY (`idLiaison`),
  INDEX `fk_Liaison_Equipement1_idx` (`idEquipement1` ASC),
  INDEX `fk_Liaison_Equipement2_idx` (`idEquipement2` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
