-- MySQL Script generated by MySQL Workbench
-- 05/19/15 10:13:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `idType` INT NOT NULL,
  `nomType` VARCHAR(45) NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lieux_Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lieux_Archive` (
  `idLieux_Archive` INT NOT NULL,
  `plateforme` VARCHAR(45) NULL,
  `batiment` VARCHAR(45) NULL,
  `salle` VARCHAR(45) NULL,
  `paclard` INT NULL,
  `colonne` INT NULL,
  PRIMARY KEY (`idLieux_Archive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fournisseur` (
  `idFournisseur` INT NOT NULL,
  `nomFournisseur` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `CP` INT NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idFournisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `nomUtilisateur` VARCHAR(45) NULL,
  `prenomUtilisateur` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `identifiantUtilisateur` VARCHAR(45) NULL,
  `mdpUtilisateur` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planning_Occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planning_Occupation` (
  `idPlanning_Occupation` INT NOT NULL,
  `dateDebut` DATETIME NULL,
  `dateFin` DATETIME NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPlanning_Occupation`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Planning_Occupation_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Planning_Occupation_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Panne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Panne` (
  `idPanne` INT NOT NULL,
  `nomPanne` VARCHAR(45) NULL,
  `datePanne` DATETIME NULL,
  `finPanne` DATETIME NULL,
  `description` VARCHAR(200) NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPanne`, `idUtilisateur`),
  INDEX `fk_Panne_Utilisateur1_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_Panne_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT NOT NULL,
  `nomCategorie` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipement` (
  `idEquipement` INT NOT NULL,
  `etiquette` INT NULL,
  `nomEquiment` VARCHAR(45) NULL,
  `idType` INT NOT NULL,
  `idLieux_Archive` INT NOT NULL,
  `idFournisseur` INT NOT NULL,
  `idPlanning_Occupation` INT NOT NULL,
  `idPanne` INT NOT NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idType`, `idLieux_Archive`, `idFournisseur`, `idPlanning_Occupation`, `idPanne`, `idCategorie`),
  INDEX `fk_Equipement_Type_idx` (`idType` ASC),
  INDEX `fk_Equipement_Lieux_Archive1_idx` (`idLieux_Archive` ASC),
  INDEX `fk_Equipement_Fournisseur1_idx` (`idFournisseur` ASC),
  INDEX `fk_Equipement_Planning_Occupation1_idx` (`idPlanning_Occupation` ASC),
  INDEX `fk_Equipement_Panne1_idx` (`idPanne` ASC),
  INDEX `fk_Equipement_Categorie1_idx` (`idCategorie` ASC),
  CONSTRAINT `fk_Equipement_Type`
    FOREIGN KEY (`idType`)
    REFERENCES `mydb`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_Lieux_Archive1`
    FOREIGN KEY (`idLieux_Archive`)
    REFERENCES `mydb`.`Lieux_Archive` (`idLieux_Archive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_Fournisseur1`
    FOREIGN KEY (`idFournisseur`)
    REFERENCES `mydb`.`Fournisseur` (`idFournisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_Planning_Occupation1`
    FOREIGN KEY (`idPlanning_Occupation`)
    REFERENCES `mydb`.`Planning_Occupation` (`idPlanning_Occupation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_Panne1`
    FOREIGN KEY (`idPanne`)
    REFERENCES `mydb`.`Panne` (`idPanne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Document` (
  `idDocument` INT NOT NULL,
  `Document` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipement_has_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipement_has_Document` (
  `idEquipement` INT NOT NULL,
  `idDocument` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idDocument`),
  INDEX `fk_Equipement_has_Document_Document1_idx` (`idDocument` ASC),
  INDEX `fk_Equipement_has_Document_Equipement1_idx` (`idEquipement` ASC),
  CONSTRAINT `fk_Equipement_has_Document_Equipement1`
    FOREIGN KEY (`idEquipement`)
    REFERENCES `mydb`.`Equipement` (`idEquipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_has_Document_Document1`
    FOREIGN KEY (`idDocument`)
    REFERENCES `mydb`.`Document` (`idDocument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entretient` (
  `idEntretient` INT NOT NULL,
  `dateEntretient` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idEntretient`, `idUtilisateur`),
  INDEX `fk_Entretient_Utilisateur1_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_Entretient_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipement_has_Entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipement_has_Entretient` (
  `idEquipement` INT NOT NULL,
  `idEntretient` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idEntretient`),
  INDEX `fk_Equipement_has_Entretient_Entretient1_idx` (`idEntretient` ASC),
  INDEX `fk_Equipement_has_Entretient_Equipement1_idx` (`idEquipement` ASC),
  CONSTRAINT `fk_Equipement_has_Entretient_Equipement1`
    FOREIGN KEY (`idEquipement`)
    REFERENCES `mydb`.`Equipement` (`idEquipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipement_has_Entretient_Entretient1`
    FOREIGN KEY (`idEntretient`)
    REFERENCES `mydb`.`Entretient` (`idEntretient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Liaison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Liaison` (
  `idLiaison` INT NOT NULL,
  `idEquipement1` INT NOT NULL,
  `idEquipement2` INT NOT NULL,
  PRIMARY KEY (`idLiaison`),
  INDEX `fk_Liaison_Equipement1_idx` (`idEquipement1` ASC),
  INDEX `fk_Liaison_Equipement2_idx` (`idEquipement2` ASC),
  CONSTRAINT `fk_Liaison_Equipement1`
    FOREIGN KEY (`idEquipement1`)
    REFERENCES `mydb`.`Equipement` (`idEquipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Liaison_Equipement2`
    FOREIGN KEY (`idEquipement2`)
    REFERENCES `mydb`.`Equipement` (`idEquipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
