-- MySQL Script generated by MySQL Workbench
-- 06/09/15 09:07:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qualite
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qualite` ;

-- -----------------------------------------------------
-- Schema qualite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qualite` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `qualite` ;

-- -----------------------------------------------------
-- Table `qualite`.`fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`fournisseur` (
  `idFournisseur` INT NOT NULL AUTO_INCREMENT,
  `nomFournisseur` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `telephone` TEXT(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idFournisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`equipement` (
  `idEquipement` INT NOT NULL AUTO_INCREMENT,
  `nomEquipement` VARCHAR(45) NULL,
  `idFournisseur` INT NOT NULL,
  `dateAjout` DATE NULL,
  `prix` DOUBLE NULL,
  `marque` VARCHAR(45) NULL,
  `dateFabrication` DATE NULL,
  `dateReception` DATE NULL,
  `dateMiseService` DATE NULL,
  `garantie` INT NULL,
  PRIMARY KEY (`idEquipement`, `idFournisseur`),
  INDEX `fk_Equipement_Fournisseur1_idx` (`idFournisseur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`type_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`type_document` (
  `idType_Document` INT NOT NULL AUTO_INCREMENT,
  `valeurTypeDoc` VARCHAR(45) NULL,
  `typeDocument` VARCHAR(45) NULL,
  PRIMARY KEY (`idType_Document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`processus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`processus` (
  `idProcessus` INT NOT NULL AUTO_INCREMENT,
  `valeurProcessus` VARCHAR(45) NULL,
  `Processus` VARCHAR(45) NULL,
  PRIMARY KEY (`idProcessus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`sous_processus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`sous_processus` (
  `idSous_Processus` INT NOT NULL AUTO_INCREMENT,
  `valeurSousProcessus` VARCHAR(45) NULL,
  `sousProcessus` VARCHAR(45) NULL,
  PRIMARY KEY (`idSous_Processus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`categorie_etiquette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`categorie_etiquette` (
  `idCategorieEtiquette` INT NOT NULL AUTO_INCREMENT,
  `valeurCategorie` VARCHAR(45) NULL,
  `categorieEtiquette` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorieEtiquette`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`acronime_etiquette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`acronime_etiquette` (
  `idAcronimeEtiquette` INT NOT NULL AUTO_INCREMENT,
  `valeurAcronime` VARCHAR(45) NULL,
  `acronimeEtiquette` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcronimeEtiquette`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`etiquette_equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`etiquette_equipement` (
  `idEtiquette_Equipement` INT NOT NULL AUTO_INCREMENT,
  `idCategorieEtiquette` INT NOT NULL,
  `idAcronimeEtiquette` INT NOT NULL,
  `idEquipement` INT NOT NULL,
  PRIMARY KEY (`idEtiquette_Equipement`, `idCategorieEtiquette`, `idAcronimeEtiquette`, `idEquipement`),
  INDEX `fk_Etiquette_Equipement_Categorie_Etiquette1_idx` (`idCategorieEtiquette` ASC),
  INDEX `fk_Etiquette_Equipement_Equipement1_idx` (`idEquipement` ASC),
  INDEX `fk_Etiquette_Equipement_Acronime_Etiquette1_idx` (`idAcronimeEtiquette` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`etiquette_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`etiquette_document` (
  `idEtiquette_Document` INT NOT NULL AUTO_INCREMENT,
  `idType_Document` INT NOT NULL,
  `idProcessus` INT NOT NULL,
  `idSous_Processus` INT NOT NULL,
  `idEtiquette_Equipement` INT NOT NULL,
  PRIMARY KEY (`idEtiquette_Document`, `idType_Document`, `idProcessus`, `idSous_Processus`, `idEtiquette_Equipement`),
  INDEX `fk_Etiquette_Document_Type_Document1_idx` (`idType_Document` ASC),
  INDEX `fk_Etiquette_Document_Processus1_idx` (`idProcessus` ASC),
  INDEX `fk_Etiquette_Document_Sous_Processus1_idx` (`idSous_Processus` ASC),
  INDEX `fk_Etiquette_Document_Etiquette_Equipement1_idx` (`idEtiquette_Equipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`plateforme_archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`plateforme_archive` (
  `idPlateforme_Archive` INT NOT NULL AUTO_INCREMENT,
  `plateformeArchive` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlateforme_Archive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`piece_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`piece_document` (
  `idPiece_Document` INT NOT NULL AUTO_INCREMENT,
  `pieceDocument` VARCHAR(45) NULL,
  PRIMARY KEY (`idPiece_Document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`emplacement_archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`emplacement_archive` (
  `idEmplacement_Archive` INT NOT NULL AUTO_INCREMENT,
  `emplacementArchive` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmplacement_Archive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`sous_emplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`sous_emplacement` (
  `idSous_Emplacement` INT NOT NULL AUTO_INCREMENT,
  `sousEmplacement` VARCHAR(45) NULL,
  PRIMARY KEY (`idSous_Emplacement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`lieux_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`lieux_document` (
  `idLieux_Document` INT NOT NULL AUTO_INCREMENT,
  `idPlateforme_Archive` INT NOT NULL,
  `idPiece_Document` INT NOT NULL,
  `idEmplacement_Archive` INT NOT NULL,
  `idSous_Emplacement` INT NOT NULL,
  PRIMARY KEY (`idLieux_Document`, `idPlateforme_Archive`, `idPiece_Document`, `idEmplacement_Archive`, `idSous_Emplacement`),
  INDEX `fk_Lieux_Document_Plateforme_Archive1_idx` (`idPlateforme_Archive` ASC),
  INDEX `fk_Lieux_Document_Piece_Document1_idx` (`idPiece_Document` ASC),
  INDEX `fk_Lieux_Document_Emplacement_Archive1_idx` (`idEmplacement_Archive` ASC),
  INDEX `fk_Lieux_Document_Sous_Emplacement1_idx` (`idSous_Emplacement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`document` (
  `idDocument` INT NOT NULL AUTO_INCREMENT,
  `nomDocument` VARCHAR(45) NULL,
  `idEtiquette_Document` INT NOT NULL,
  `idLieux_Document` INT NOT NULL,
  PRIMARY KEY (`idDocument`, `idEtiquette_Document`, `idLieux_Document`),
  INDEX `fk_Document_Etiquette_Document1_idx` (`idEtiquette_Document` ASC),
  INDEX `fk_Document_Lieux_Document1_idx` (`idLieux_Document` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(45) NULL,
  `prenomUtilisateur` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`fonction_secondaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`fonction_secondaire` (
  `idFonction_Secondaire` INT NOT NULL AUTO_INCREMENT,
  `fonctionSecondaire` VARCHAR(45) NULL,
  PRIMARY KEY (`idFonction_Secondaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`fonction_principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`fonction_principal` (
  `idFonction_Principal` INT NOT NULL AUTO_INCREMENT,
  `fonctionPrincipal` VARCHAR(45) NULL,
  `idFonction_Secondaire` INT NOT NULL,
  PRIMARY KEY (`idFonction_Principal`, `idFonction_Secondaire`),
  INDEX `fk_Fonction_Principal_Fonction_Secondaire1_idx` (`idFonction_Secondaire` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`piece_equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`piece_equipement` (
  `idPiece` INT NOT NULL AUTO_INCREMENT,
  `valeur` VARCHAR(45) NULL,
  `piece` VARCHAR(45) NULL,
  `idFonction_Principal` INT NOT NULL,
  PRIMARY KEY (`idPiece`, `idFonction_Principal`),
  INDEX `fk_Piece_Equipement_Fonction_Principal1_idx` (`idFonction_Principal` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`lieu_utilisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`lieu_utilisation` (
  `idLieu_Utilisation` INT NOT NULL AUTO_INCREMENT,
  `lieuUtilisation` VARCHAR(45) NULL,
  `idPiece` INT NOT NULL,
  PRIMARY KEY (`idLieu_Utilisation`, `idPiece`),
  INDEX `fk_Lieu_Equipement_Piece_Equipement1_idx` (`idPiece` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`plateforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`plateforme` (
  `idPlateforme` INT NOT NULL AUTO_INCREMENT,
  `plateforme` VARCHAR(45) NULL,
  `idLieu_Utilisation` INT NOT NULL,
  PRIMARY KEY (`idPlateforme`, `idLieu_Utilisation`),
  INDEX `fk_Plateforme_Lieu_Equipement1_idx` (`idLieu_Utilisation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`lieu_quipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`lieu_quipement` (
  `idLieu_Equipement` INT NOT NULL AUTO_INCREMENT,
  `idEquipement` INT NOT NULL,
  `idPlateforme` INT NOT NULL,
  PRIMARY KEY (`idLieu_Equipement`, `idEquipement`, `idPlateforme`),
  INDEX `fk_Lieu_Equipement_Plateforme1_idx` (`idPlateforme` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`planning_occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`planning_occupation` (
  `idPlanning_Occupation` INT NOT NULL AUTO_INCREMENT,
  `dateDebut` DATETIME NULL,
  `dateFin` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  `idLieu_Equipement` INT NOT NULL,
  PRIMARY KEY (`idPlanning_Occupation`, `idUtilisateur`, `idLieu_Equipement`),
  INDEX `fk_Planning_Occupation_Utilisateur1_idx` (`idUtilisateur` ASC),
  INDEX `fk_Planning_Occupation_Lieu_Equipement1_idx` (`idLieu_Equipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`equipement_has_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`equipement_has_document` (
  `idEquipement` INT NOT NULL,
  `idDocument` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idDocument`),
  INDEX `fk_Equipement_has_Document_Document1_idx` (`idDocument` ASC),
  INDEX `fk_Equipement_has_Document_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`entretient` (
  `idEntretient` INT NOT NULL AUTO_INCREMENT,
  `dateEntretient` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idEntretient`, `idUtilisateur`),
  INDEX `fk_Entretient_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`equipement_has_entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`equipement_has_entretient` (
  `idEquipement` INT NOT NULL,
  `idEntretient` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idEntretient`),
  INDEX `fk_Equipement_has_Entretient_Entretient1_idx` (`idEntretient` ASC),
  INDEX `fk_Equipement_has_Entretient_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`liaison_equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`liaison_equipement` (
  `idLiaison_Equipement` INT NOT NULL AUTO_INCREMENT,
  `idEquipement1` INT NOT NULL,
  `idEquipement2` INT NOT NULL,
  PRIMARY KEY (`idLiaison_Equipement`, `idEquipement1`, `idEquipement2`),
  INDEX `fk_Liaison_Equipement1_idx` (`idEquipement1` ASC),
  INDEX `fk_Liaison_Equipement2_idx` (`idEquipement2` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`anomalie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`anomalie` (
  `idAnomalie` INT NOT NULL AUTO_INCREMENT,
  `nomAnomalie` VARCHAR(45) NULL,
  `dateAnomalie` DATETIME NULL,
  `finAnomalie` DATETIME NULL,
  `description` VARCHAR(200) NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idAnomalie`, `idUtilisateur`),
  INDEX `fk_Panne_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`equipement_has_anomalie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`equipement_has_anomalie` (
  `idEquipement` INT NOT NULL,
  `idAnomalie` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idAnomalie`),
  INDEX `fk_Equipement_has_Panne_Panne1_idx` (`idAnomalie` ASC),
  INDEX `fk_Equipement_has_Panne_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`equipement_has_planning_occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`equipement_has_planning_occupation` (
  `idEquipement` INT NOT NULL,
  `idPlanning_Occupation` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idPlanning_Occupation`),
  INDEX `fk_Equipement_has_Planning_Occupation_Planning_Occupation1_idx` (`idPlanning_Occupation` ASC),
  INDEX `fk_Equipement_has_Planning_Occupation_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualite`.`acronime_has_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualite`.`acronime_has_categorie` (
  `idCategorieEtiquette` INT NOT NULL,
  `idAcronimeEtiquette` INT NOT NULL,
  PRIMARY KEY (`idCategorieEtiquette`, `idAcronimeEtiquette`),
  INDEX `fk_Acronime_Etiquette_has_Categorie_Etiquette_Categorie_Eti_idx` (`idCategorieEtiquette` ASC),
  INDEX `fk_Acronime_Etiquette_has_Categorie_Etiquette_Acronime_Etiq_idx` (`idAcronimeEtiquette` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
