-- MySQL Script generated by MySQL Workbench
-- 05/29/15 10:23:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecotron
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecotron` ;

-- -----------------------------------------------------
-- Schema ecotron
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecotron` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ecotron` ;

-- -----------------------------------------------------
-- Table `ecotron`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `nomType` VARCHAR(45) NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Fournisseur` (
  `idFournisseur` INT NOT NULL AUTO_INCREMENT,
  `nomFournisseur` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `telephone` TEXT(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idFournisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement` (
  `idEquipement` INT NOT NULL AUTO_INCREMENT,
  `nomEquiment` VARCHAR(45) NULL,
  `idType` INT NOT NULL,
  `idFournisseur` INT NOT NULL,
  `dateAjout` DATE NULL,
  `prix` DOUBLE NULL,
  `marque` VARCHAR(45) NULL,
  `anneeFabrication` DATE NULL,
  `dateReception` DATE NULL,
  `dateMiseService` DATE NULL,
  `garantie` INT NULL,
  PRIMARY KEY (`idEquipement`, `idType`, `idFournisseur`),
  INDEX `fk_Equipement_Type_idx` (`idType` ASC),
  INDEX `fk_Equipement_Fournisseur1_idx` (`idFournisseur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Categorie_Etiquette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Categorie_Etiquette` (
  `idCategorieEtiquette` INT NOT NULL AUTO_INCREMENT,
  `categorieEtiquette` VARCHAR(45) NULL,
  `valeurCategorie` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorieEtiquette`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`EtiEquipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`EtiEquipement` (
  `idEtiEquipement` INT NOT NULL AUTO_INCREMENT,
  `idCategorieEtiquette` INT NOT NULL,
  PRIMARY KEY (`idEtiEquipement`, `idCategorieEtiquette`),
  INDEX `fk_EtiEquipement_Categorie_Etiquette1_idx` (`idCategorieEtiquette` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Numero_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Numero_Document` (
  `idNumero_Document` INT NOT NULL AUTO_INCREMENT,
  `idEtiEquipement` INT NOT NULL,
  PRIMARY KEY (`idNumero_Document`, `idEtiEquipement`),
  INDEX `fk_Numero_Document_EtiEquipement1_idx` (`idEtiEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Sous_Processus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Sous_Processus` (
  `idSous_Processus` INT NOT NULL AUTO_INCREMENT,
  `sousProcessus` VARCHAR(45) NULL,
  `idNumero_Document` INT NOT NULL,
  PRIMARY KEY (`idSous_Processus`, `idNumero_Document`),
  INDEX `fk_Sous_Processus_Numero_Document1_idx` (`idNumero_Document` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Processus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Processus` (
  `idProcessus` INT NOT NULL AUTO_INCREMENT,
  `Processus` VARCHAR(45) NULL,
  `idSous_Processus` INT NOT NULL,
  PRIMARY KEY (`idProcessus`, `idSous_Processus`),
  INDEX `fk_Processus_Sous_Processus1_idx` (`idSous_Processus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Type_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Type_Document` (
  `idType_Document` INT NOT NULL AUTO_INCREMENT,
  `typeDocument` VARCHAR(45) NULL,
  `idProcessus` INT NOT NULL,
  PRIMARY KEY (`idType_Document`, `idProcessus`),
  INDEX `fk_Type_Document_Processus1_idx` (`idProcessus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Etiquette_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Etiquette_Document` (
  `idEtiquette_Document` INT NOT NULL AUTO_INCREMENT,
  `idType_Document` INT NOT NULL,
  PRIMARY KEY (`idEtiquette_Document`, `idType_Document`),
  INDEX `fk_Etiquette_Document_Type_Document1_idx` (`idType_Document` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Sous_Emplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Sous_Emplacement` (
  `idSous_Emplacement` INT NOT NULL AUTO_INCREMENT,
  `sousEmplacement` VARCHAR(45) NULL,
  PRIMARY KEY (`idSous_Emplacement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Emplacement_Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Emplacement_Archive` (
  `idEmplacement_Archive` INT NOT NULL AUTO_INCREMENT,
  `emplacementArchive` VARCHAR(45) NULL,
  `idSous_Emplacement` INT NOT NULL,
  PRIMARY KEY (`idEmplacement_Archive`, `idSous_Emplacement`),
  INDEX `fk_Emplacement_Archive_Sous_Emplacement1_idx` (`idSous_Emplacement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Piece_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Piece_Document` (
  `idPiece_Document` INT NOT NULL AUTO_INCREMENT,
  `pieceDocument` VARCHAR(45) NULL,
  `idEmplacement_Archive` INT NOT NULL,
  PRIMARY KEY (`idPiece_Document`, `idEmplacement_Archive`),
  INDEX `fk_Piece_Document_Emplacement_Archive1_idx` (`idEmplacement_Archive` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Plateforme_Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Plateforme_Archive` (
  `idPlateforme_Archive` INT NOT NULL AUTO_INCREMENT,
  `plateformeArchive` VARCHAR(45) NULL,
  `idPiece_Document` INT NOT NULL,
  PRIMARY KEY (`idPlateforme_Archive`, `idPiece_Document`),
  INDEX `fk_Plateforme_Archive_Piece_Document1_idx` (`idPiece_Document` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Lieux_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Lieux_Document` (
  `idLieux_Document` INT NOT NULL AUTO_INCREMENT,
  `idPlateforme_Archive` INT NOT NULL,
  PRIMARY KEY (`idLieux_Document`, `idPlateforme_Archive`),
  INDEX `fk_Lieux_Document_Plateforme_Archive1_idx` (`idPlateforme_Archive` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Document` (
  `idDocument` INT NOT NULL AUTO_INCREMENT,
  `nomDocument` VARCHAR(45) NULL,
  `idEtiquette_Document` INT NOT NULL,
  `idLieux_Document` INT NOT NULL,
  PRIMARY KEY (`idDocument`, `idEtiquette_Document`, `idLieux_Document`),
  INDEX `fk_Document_Etiquette_Document1_idx` (`idEtiquette_Document` ASC),
  INDEX `fk_Document_Lieux_Document1_idx` (`idLieux_Document` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(45) NULL,
  `prenomUtilisateur` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Fonction_Secondaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Fonction_Secondaire` (
  `idFonction_Secondaire` INT NOT NULL AUTO_INCREMENT,
  `fonctionSecondaire` VARCHAR(45) NULL,
  PRIMARY KEY (`idFonction_Secondaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Fonction_Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Fonction_Principal` (
  `idFonction_Principal` INT NOT NULL AUTO_INCREMENT,
  `fonctionPrincipal` VARCHAR(45) NULL,
  `idFonction_Secondaire` INT NOT NULL,
  PRIMARY KEY (`idFonction_Principal`, `idFonction_Secondaire`),
  INDEX `fk_Fonction_Principal_Fonction_Secondaire1_idx` (`idFonction_Secondaire` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Piece_Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Piece_Equipement` (
  `idPiece` INT NOT NULL AUTO_INCREMENT,
  `valeur` VARCHAR(45) NULL,
  `piece` VARCHAR(45) NULL,
  `idFonction_Principal` INT NOT NULL,
  PRIMARY KEY (`idPiece`, `idFonction_Principal`),
  INDEX `fk_Piece_Equipement_Fonction_Principal1_idx` (`idFonction_Principal` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Lieu_Utilisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Lieu_Utilisation` (
  `idLieu_Utilisation` INT NOT NULL AUTO_INCREMENT,
  `lieuEquipement` VARCHAR(45) NULL,
  `idPiece` INT NOT NULL,
  PRIMARY KEY (`idLieu_Utilisation`, `idPiece`),
  INDEX `fk_Lieu_Equipement_Piece_Equipement1_idx` (`idPiece` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Plateforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Plateforme` (
  `idPlateforme` INT NOT NULL AUTO_INCREMENT,
  `plateforme` VARCHAR(45) NULL,
  `idLieu_Utilisation` INT NOT NULL,
  PRIMARY KEY (`idPlateforme`, `idLieu_Utilisation`),
  INDEX `fk_Plateforme_Lieu_Equipement1_idx` (`idLieu_Utilisation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Lieu_Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Lieu_Equipement` (
  `idLieu_Equipement` INT NOT NULL AUTO_INCREMENT,
  `idEquipement` INT NOT NULL,
  `idPlateforme` INT NOT NULL,
  PRIMARY KEY (`idLieu_Equipement`, `idEquipement`, `idPlateforme`),
  INDEX `fk_Lieu_Equipement_Plateforme1_idx` (`idPlateforme` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Planning_Occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Planning_Occupation` (
  `idPlanning_Occupation` INT NOT NULL AUTO_INCREMENT,
  `dateDebut` DATETIME NULL,
  `dateFin` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  `idLieu_Equipement` INT NOT NULL,
  PRIMARY KEY (`idPlanning_Occupation`, `idUtilisateur`, `idLieu_Equipement`),
  INDEX `fk_Planning_Occupation_Utilisateur1_idx` (`idUtilisateur` ASC),
  INDEX `fk_Planning_Occupation_Lieu_Equipement1_idx` (`idLieu_Equipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement_has_Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement_has_Document` (
  `idEquipement` INT NOT NULL,
  `idDocument` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idDocument`),
  INDEX `fk_Equipement_has_Document_Document1_idx` (`idDocument` ASC),
  INDEX `fk_Equipement_has_Document_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Entretient` (
  `idEntretient` INT NOT NULL AUTO_INCREMENT,
  `dateEntretient` DATETIME NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idEntretient`, `idUtilisateur`),
  INDEX `fk_Entretient_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement_has_Entretient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement_has_Entretient` (
  `idEquipement` INT NOT NULL,
  `idEntretient` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idEntretient`),
  INDEX `fk_Equipement_has_Entretient_Entretient1_idx` (`idEntretient` ASC),
  INDEX `fk_Equipement_has_Entretient_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Liaison_Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Liaison_Equipement` (
  `idLiaison_Equipement` INT NOT NULL AUTO_INCREMENT,
  `idEquipement1` INT NOT NULL,
  `idEquipement2` INT NOT NULL,
  PRIMARY KEY (`idLiaison_Equipement`, `idEquipement1`, `idEquipement2`),
  INDEX `fk_Liaison_Equipement1_idx` (`idEquipement1` ASC),
  INDEX `fk_Liaison_Equipement2_idx` (`idEquipement2` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Anomalie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Anomalie` (
  `idAnomalie` INT NOT NULL AUTO_INCREMENT,
  `nomAnomalie` VARCHAR(45) NULL,
  `dateAnomalie` DATETIME NULL,
  `finAnomalie` DATETIME NULL,
  `description` VARCHAR(200) NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idAnomalie`, `idUtilisateur`),
  INDEX `fk_Panne_Utilisateur1_idx` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement_has_Anomalie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement_has_Anomalie` (
  `idEquipement` INT NOT NULL,
  `idAnomalie` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idAnomalie`),
  INDEX `fk_Equipement_has_Panne_Panne1_idx` (`idAnomalie` ASC),
  INDEX `fk_Equipement_has_Panne_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Equipement_has_Planning_Occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Equipement_has_Planning_Occupation` (
  `idEquipement` INT NOT NULL,
  `idPlanning_Occupation` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idPlanning_Occupation`),
  INDEX `fk_Equipement_has_Planning_Occupation_Planning_Occupation1_idx` (`idPlanning_Occupation` ASC),
  INDEX `fk_Equipement_has_Planning_Occupation_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Etiquette_Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Etiquette_Equipement` (
  `idEquipement` INT NOT NULL,
  `idCategorieEtiquette` INT NOT NULL,
  PRIMARY KEY (`idEquipement`, `idCategorieEtiquette`),
  INDEX `fk_Etiquette_Equipement_Categorie_Etiquette1_idx` (`idCategorieEtiquette` ASC),
  INDEX `fk_Etiquette_Equipement_Equipement1_idx` (`idEquipement` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Acronime_Etiquette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Acronime_Etiquette` (
  `idAcronimeEtiquette` INT NOT NULL AUTO_INCREMENT,
  `valeurAcronime` VARCHAR(45) NULL,
  `acronimeEtiquette` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcronimeEtiquette`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecotron`.`Acronime_has_Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecotron`.`Acronime_has_Categorie` (
  `idAcronimeEtiquette` INT NOT NULL,
  `idCategorieEtiquette` INT NOT NULL,
  PRIMARY KEY (`idAcronimeEtiquette`, `idCategorieEtiquette`),
  INDEX `fk_Acronime_Etiquette_has_Categorie_Etiquette_Categorie_Eti_idx` (`idCategorieEtiquette` ASC),
  INDEX `fk_Acronime_Etiquette_has_Categorie_Etiquette_Acronime_Etiq_idx` (`idAcronimeEtiquette` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
